name: Composer CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Upload DAGs
        run: |
          DATASET=$(yq e '.dataset' script_execution.yml)

          FOLDER="$DATASET/dags"

          if [ ! -d "$FOLDER" ]; then
            echo "❌ DAG folder not found"
            exit 1
          fi

          gsutil -m cp "$FOLDER"/*.py gs://us-central1-airflow3-cc018626-bucket/dags
          echo "✅ DAGs uploaded"