name: Deploy Infra

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: project-d0445eef-b5cb-453b-a9a
  REGION: us-central1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/787268830461/locations/global/workloadIdentityPools/github-pool/providers/github-provider-v2
        service_account: github-actions-sa@project-d0445eef-b5cb-453b-a9a.iam.gserviceaccount.com

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve \
        -var="project_id=$PROJECT_ID"