name: Deploy to GCP

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write   # REQUIRED for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/787268830461/locations/global/workloadIdentityPools/github-pool/providers/github-provider-v2
        service_account: github-actions-sa@project-d0445eef-b5cb-453b-a9a.iam.gserviceaccount.com

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1

    - name: Test access
      run: |
        gcloud projects list